#!/usr/bin/env python3

import sys
import list_calendars, list_events
import create_event, update_event, delete_event
import datetime, pickle, os.path

from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build

from find_credentials import find_credentials
from cal_setup import get_calendar_service


def main():
    for arg in sys.argv:
        if arg == 'login':
            credentials = find_credentials('credentials.json', search_path)
            service = get_calendar_service()
        
        # This checks for an empty second argumnet
        if len(sys.argv) < 2:
            print('\nThese are the wtc-calendar commands:\n')
            print('\t<command> [args]\n')
            print('\t\tlogin\tConnect to the Google Calendar API')
            print('\t\tstatus\tDisplays the connection status to the Google Calendar API')
            print('\t\tslots\tDisplays the open time slots that can be booked\n')



if __name__ == '__main__':
    main()