#!/bin/python3
import os
import sys
import subprocess
from login import user_auth as authentication
from bookings import list_calendars as calendar
from bookings import create_event as create


valid_sys_commands = ['register', 'status', 'login', 'logout', 'slots',
    'book', 'cancel', 'logout', 'view-cal', 'volunteer']

def command_instructions():
    """Print out statements that shows how the booking system works."""
    
    print('\nThese are wtc-cal commands that can be used in this Code Clinic:\n')

    print("\tstatus\t\tRun this command to check the connection")
    print("\tlogin\t\tRun this command to log into the calendars")
    print("\tlogout\t\tRun this command to logout of the calendar")
    print("\tslots\t\tRun this command to see all slots [BOOKED], [OPEN]")
    print("\tbook\t\tRun this command to book someone's slot")
    print("\tvolunteer\tRun this command to open a slot for someone")
    print("\tview-cal\tRun this command to view your calendar")
    print("\tcancel\t\tRun this to command cancel a bookings or a voluteering slot\n")


def command_sys_argv():
    """Different command line argument values that work with the booking system.
    """

    if len(sys.argv) == 2 and sys.argv[1] in valid_sys_commands:
        command = sys.argv[1]

        if 'status' == command:
            authentication.get_user_status()
        elif 'login' == command:
            authentication.user_login()
        elif 'logout' == command:
            authentication.user_logout()
        elif "slots" == command:
            calendar.get_slots_calendar()
        elif "view-cal" == command:
            calendar.get_student_calendar()
            # subprocess.call("./.view.sh", shell=True)
        elif "book" == command:
            pass
        elif "volunteer" == command:
            create.get_user_input()
        elif "cancel" == command:
            pass
    else:
        command_instructions()

if __name__ == "__main__":
    command_sys_argv()