#!/bin/python3

import os
import sys
# from login import user_auth as authentication
from login import user_auth
from process1 import *
# from process.list_calendars import *


valid_sys_commands = ['volunteer', 'status', 'login', 'logout', 'slots',
    'book', 'cancel', 'logout']


def command_instructions():
    """Print out statements that shows how the booking system works."""
    
    if len(sys.argv) >= 2:
        command = ""
        for arg in sys.argv[1:]:
            command += f"{arg} "
        print(f"Unrecognized command: \"wtc-cal {command.strip()}\"")
        
    elif len(sys.argv) == 1:
        print("Please provide some options")

    print('\nThese are wtc-cal commands that can be used in this Code Clinic:\n')

    print("\tstatus\t\tRun this command to check the connection")
    print("\tlogin\t\tRun this command to log into the calendars")
    print("\tslots\t\tRun this command to see all slots [BOOKED], [OPEN]")
    print("\tbook\t\tRun this command to book someone's slot")
    print("\tvolunteer\tRun this command to open a slot for someone")
    print("\tcancel\t\tRun this to command cancel a bookings or a voluteering slot\n")


def command_sys_argv():
    """Different command line argument values that work with the booking system.
    """

    if len(sys.argv) == 2 and sys.argv[1] in valid_sys_commands:
        command = sys.argv[1]

        if 'status' == command:
            user_auth.get_user_status()
        elif 'login' == command:
            user_auth.user_login()
        elif 'logout' == command:
            user_auth.user_logout()
            #Replace the true below with a boolean that will check if token exist
        elif os.path.exists("token.pickle") and command in valid_sys_commands:
            if "slots" == command:
                get_slots()
            elif "book" == command:
                book_event("etag")
            elif "volunteer" == command:
                volunteer("etag")
            elif "cancel" == command:
                cancel("etag")
        else:
            print("Token expired (some token details....) etc.\nPlease login using: \"wtc-cal login\"")
    else:
        command_instructions()


if __name__ == "__main__":
    command_sys_argv()